modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="ing_ore"
version="1.0.0"
displayName="Ing Ore"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="ClyKiddo"
description="A mod based off of Phoenix SC's video on Ing Ore"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ing_ore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration